// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqSslbzZUBcT1n72bUJK8F8VHrgsaq88A',
    appId: '1:377001966343:web:842b44e9327efb8840e3a2',
    messagingSenderId: '377001966343',
    projectId: 'webtakeru',
    authDomain: 'webtakeru.firebaseapp.com',
    storageBucket: 'webtakeru.firebasestorage.app',
    measurementId: 'G-N557JY9WRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ58m0z4Y6n7j3egJH4v1QLlriWe2xi28',
    appId: '1:377001966343:android:10e4b6903fb7026c40e3a2',
    messagingSenderId: '377001966343',
    projectId: 'webtakeru',
    storageBucket: 'webtakeru.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqSslbzZUBcT1n72bUJK8F8VHrgsaq88A',
    appId: '1:377001966343:web:161c8ba535bf9b4e40e3a2',
    messagingSenderId: '377001966343',
    projectId: 'webtakeru',
    authDomain: 'webtakeru.firebaseapp.com',
    storageBucket: 'webtakeru.firebasestorage.app',
    measurementId: 'G-74W9JXQSHM',
  );
}
